### ISSUE TITLE
Deploy Error Invalid Request from Power BI API

### ISSUE THREAD

**Issue by JT-BergerGroup** [pbi-tools/pbi-tools#132]
Hello, thanks for all the effort on this tool, much appreciated!

I am trying to set up the deployment (using RC1 locally and also using the Docker in Azure DevOps) but deployment fails with the following error message:

biTools.Deployments.DeploymentException: HTTP Error: BadRequest
{
  "error": {
    "code": "InvalidRequest",
    "message": "Invalid dataflow structure. Exception details: <pi>Invalid model version: 0.11</pi>"
  }
} ---> Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'BadRequest'
   bei Microsoft.PowerBI.Api.ImportsOperations.<UploadFile>d__8.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.PowerBI.Api.ImportsOperations.<PostImportFileWithHttpMessage>d__7.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.PowerBI.Api.ImportsOperationsExtensions.<PostImportWithFileAsyncInGroup>d__11.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PbiTools.Deployments.DeploymentManager.<ImportReportAsync>d__36.MoveNext() in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:Zeile 443.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei PbiTools.Deployments.DeploymentManager.<DeployReportAsync>d__31.MoveNext() in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:Zeile 184.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei PbiTools.Deployments.DeploymentManager.<DeployReportAsync>d__31.MoveNext() in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:Zeile 190.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:Zeile 99.<---

I am using Version: 2.105.664.0 64-bit (Mai 2022) of PBI Desktop. Any ideas or guidance would be appreciated. Thanks in advance....

**Comment by mthierba** [comment]
Hi @JT-BergerGroup, could you clarify what your deployment source is here? The error message seems to suggest that the API is expecting to receive a `model.json` file defining a PBI Dataflow (see here: https://docs.microsoft.com/en-us/rest/api/power-bi/imports/post-import-in-group#import-dataflow-model.json-example). Is that your intention? That's not a scenario I have tested `pbi-tools deploy` with.

**Comment by JT-BergerGroup** [comment]
Hello Mathias, thanks for the prompt reply, no i was not trying to deploy a dataflow, at least not intentionally. My aim would be dataset and report.

**Comment by mthierba** [comment]
Correct, with a `File` source, the Path needs to point to a `*.PBIX` file. For `Folder`, it needs to be a folder containing PbixProj sources.

**Comment by JT-BergerGroup** [comment]
I fixed the path to the correct path and now its working like a charm, both locally and on azure devOps pipeline! thanks for your support
