### ISSUE TITLE
Support deployments of incremental refresh datasets

### ISSUE THREAD

**Issue by bburner** [pbi-tools/pbi-tools#151]
When doing a folder deployment without a refresh, existing data in a dataset is replaced by an empty dataset. Is it possible to do a metadata only deployment using the folder deployment method? We have large incremental refresh models where doing a full refresh on each deployment is not practical.

**Comment by mthierba** [comment]
Supporting incremental refresh and other advanced partitioning scenarios is high priority on the roadmap. I'm currently working through workflows and manifest options for those. Not yet in the latest preview, though.
