### ISSUE TITLE
Extract command contains report level changes, that are not in accordance with the changes being made by the user.

### ISSUE THREAD

**Issue by TarekSalha** [pbi-tools/pbi-tools#161]
I am using the following version of pbi tools (rc2 pre-release)
{
  "version": "1.0.0-rc.2+20220525",
  "edition": "Desktop",
  "build": "1.0.22145.2342",
  "pbixProjVersion": "0.12",
  "pbiBuildVersion": "2.104.941.0",
  "amoVersion": "19.39.2.2",
  "toolPath": "C:\\Users\\TarekSalha\\pbi-tools\\pbi-tools.exe",
  "locale": {
    "system": "de-DE (1031)",
    "ui": "de-DE (1031)"
  },
  "runtime": {
    "platform": "Microsoft Windows 10.0.22000 ",
    "architecture": "X64",
    "framework": ".NET Framework 4.8.4510.0"
  },
  "pbiInstalls": [
    {
      "ProductVersion": "2.106.883.0 (22.06)",
      "Is64Bit": true,
      "InstallDir": "C:\\Program Files\\WindowsApps\\Microsoft.MicrosoftPowerBIDesktop_2.106.883.0_x64__8wekyb3d8bbwe\\bin",
      "SettingsDir": "C:\\Users\\TarekSalha\\Microsoft\\Power BI Desktop Store App",
      "Location": "WindowsStore"
    },
    {
      "ProductVersion": "2.105.1143.0 (22.05)",
      "Is64Bit": true,
      "InstallDir": "C:\\Program Files\\Microsoft Power BI Desktop\\bin",
      "SettingsDir": "C:\\Users\\TarekSalha\\AppData\\Local\\Microsoft\\Power BI Desktop",
      "Location": "Installer"
    }

When using ordinary reports, the changes being made by the user in the pbix file and the results after performing the extract command are in perfect accordance. However, we have got some reports, that make extensive use of calculation groups. From our testing, we could confirm, that all changes concerning the data model are as well fine, but report-level changes are somewhat unpredictable. When performing the slightest change (e.g. activating "show items with no data" in one visual) triggers not only associated changes in the json files, but instead also alters query.json and dataTransforms.json files of all pages of all visuals using one of the calculation groups. This is somewhat unpredictable, but I could isolate some basic cases.

![image](https://user-images.githubusercontent.com/25264670/177521957-4a42dd21-b31a-469d-9afc-904aa8c4cfff.png)

I attached one sample file [test.zip](https://github.com/pbi-tools/pbi-tools/files/9053741/test.zip), that shows the problem. Steps to reproduce:
- open the file
- switch measure selection from "Sum" to "Max" and back again to "Sum"
- save the pbix file
- use "pbi-tools extract" command to extract source code to a git repo
- check source control unwanted changes (see picture) and stage changes
- switch from page 1 to page 2 and back again to page 1
- save the pbix file
- use "pbi-tools extract" command
- check source control again unwanted changes (see picture)

best regards, Tarek

**Comment by mthierba** [comment]
Hi @TarekSalha , both `query.json` as well as `dataTransforms.json` are optional files and can be safely ignored and removed from the report sources. There absence will in no way affect the functioning of the report. But as you have discovered, changes in those files can get quite noisy (they effectively cache UI state).

**Comment by mthierba** [comment]
Recommend to use this as a standard `.gitignore`: https://github.com/pbi-tools/report-devops-demo/blob/main/.gitignore

**Comment by TarekSalha** [comment]
Thanks for the explanation and suggestion. This makes perfect sense. We will ignore them in future.
