### ISSUE TITLE
Compile PBIX from source with data model

### ISSUE THREAD

**Issue by nhey** [pbi-tools/pbi-tools#162]
[Is not implemented](https://github.com/pbi-tools/pbi-tools/blob/435c7ab3c9defb55efd3d62d44b3e7bae59f18da/src/PBI-Tools/Model/PbixModel.cs#L331).

Hi, thanks for the useful project.
I could not find an open issue on this. I hope you can help me here:
* What needs to be done to implement this/why is it not possible?
* Would it be possible/easier to compile a PBIX file if the data was not actually loaded?
  (E.g. for publishing as part of pipeline and later refreshing data)

**Comment by serg-razum-off** [comment]
Hello, @mthierba / Mathias

Thanks a lot for the amazing tool. I was also trying to compile file to .pbix yet figured out that metadata knows nothing about data, so file with the data model can be compiled only into .pbit.
Yet today I saw this presentation on filters issue fixing 
https://youtu.be/Zdcb66dUM0Q?t=387
Do I understand correctly that no data model is present in this scenario?
And if so -- still, can you share the trick of how you utilized the Ctrl+Shift+B for compilation purpose?
Many thanks in advance!

**Comment by serg-razum-off** [comment]
Things are becoming interesting with VS code keybindings. 
Code below sends 2 terminal commands to compile .pbit and to open it. A lot of things become possible.
`
{
        "key": "ctrl+shift+b",
        "command": "workbench.action.terminal.sendSequence",
        "args": {
            "text": "$folder = './AdvWorksDW2020/'; $filePath ='./AdvWorksDW2020.pbit'; pbi-tools compile-pbix -folder $folder  -format PBIT -overwrite; pbi-tools.exe launch-pbi $filePath"
        }
    },
`
