### ISSUE TITLE
PBI-Tools Extract does not work

### ISSUE THREAD

**Issue by zuerichris** [pbi-tools/pbi-tools#163]
Performing the Extract action does not work, I could not find any help...

PS C:\tools\test> pbi-tools extract ".\Adventure Works DW 2020.pbix"

Error:
**_No action was specified_**

On pbi-tool info , the tool does not find the installation path of PowerBi (installed with Company Portal (Intune))

"pbi-tools extract -?" does also not show the help for the Extract - Action! 

Any ideas?

Windows 10

**Comment by mthierba** [comment]
Hi @zuerichris , there are two editions of `pbi-tools`, Desktop and Core, see here for a complete comparison: https://pbi.tools/cli/feature-matrix.html

Only the Desktop edition, which is meant to be used by developers alongside Power BI Desktop, supports the `extract` action. It appears that you installed the Core version instead, which is limited to cross-platform DevOps actions.

`pbi-tools info` reports the edition label, in case you want to check.

**Comment by zuerichris** [comment]
Great, thanks for the quick reply. Changed that, works now perfectly!
