### ISSUE TITLE
An unhandled exception occurred.

### ISSUE THREAD

**Issue by jiaopengzi** [pbi-tools/pbi-tools#177]
hi guru of Mathias

I have the following problem when using the  command line `pbi-tools deploy 164 test`

My pbixproj.json is as follows. When deployed, I can't find anywhere to log in to Power BI messages.

I guess my command line method may not be correct, please give me some guidance.

Thank you very much.

cmd
```
D:\Desktop\demo_164>pbi-tools deploy 164 test
```
message

```
D:\Desktop\demo_164>pbi-tools deploy 164 test
Reading PBIXPROJ settings from: D:\Desktop\demo_164\164\.pbixproj.json
An unhandled exception occurred.
System.AggregateException: 发生一个或多个错误。 ---> PbiTools.Deployments.DeploymentException: The current project does not contain the specified deploymment 'test'
   在 PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() 位置 X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:行号 93
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   在 PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) 位置 X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Cli\Deploy.cs:行号 39
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 PowerArgs.ArgAction.Invoke()
   在 PbiTools.Program.Main(String[] args) 位置 X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Program.cs:行号 94
---> (内部异常 #0) PbiTools.Deployments.DeploymentException: The current project does not contain the specified deploymment 'test'
   在 PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() 位置 X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Deployments\DeploymentManager.cs:行号 93<---
```

pbixproj.json
```
{
  "version": "0.11",
  "created": "2022-08-14T18:11:37.8751325+08:00",
  "lastModified": "2022-08-14T18:11:38.1752444+08:00"
}
```

Power BI version：2.108.603.0 64-bit (2022-8)
pbi-tools version：pbi-tools.1.0.0-rc.1

**Comment by jiaopengzi** [comment]
Please help look at the above questions, thank you. @mthierba

**Comment by mthierba** [comment]
Hi,
die CLI syntax for the 'deploy' command is documented here: https://pbi.tools/cli/usage-core.html#deploy

```
deploy <folder> <label> [<environment>] [<basePath>] [<whatIf>] 
```

What your command, "D:\Desktop\demo_164>pbi-tools deploy 164 test", will do is to:
- Find a manifest file in the folder "164" (relative to the working directory), hence at "D:\Desktop\demo_164\164\.pbixproj.json"
- Execute the "test" deployment profile inside the manifest
- Deploy to the "Development" environment (that's the default which is effective if no environment is specified

The pbixproj file you've quoted above is not a deployment manifest.
You can find a number of publicly available deployment manifests here: https://github.com/search?q=user%3Apbi-tools+filename%3A.pbixproj.json+path%3A%2F&type=Code

- Simple report deployment: https://github.com/pbi-tools/report-devops-demo/blob/main/.pbixproj.json
- Simple dataset deployment: https://github.com/pbi-tools/dataset-devops-demo/blob/main/.pbixproj.json

**Comment by jiaopengzi** [comment]
> 

@mthierba 
Thank you so much.
I also sent an email to your email (mathias@pbitools.org) and look forward to your reply.

**Comment by jiaopengzi** [comment]
hi，@mthierba
I emailed you and look forward to your reply.
Very presumptuous, I sent both mailboxes，mathias@pbitools.org and mt-dev@outlook.com

**Comment by jiaopengzi** [comment]
hi @mthierba
I have a question.

From the version: 1.0.0-rc.1 is the latest, but from your time release 1.0.0-rc.2+preview.5 Anniversary Release is the latest. 

Which version do you recommend?

**In addition, the gadget I wrote will be released soon, I hope to get your permission, I sent you the specific information.**

![7005932647154d138d8f3f664e17e29](https://user-images.githubusercontent.com/52224629/202463446-ebb4c00f-7167-4ca7-b61c-f95f00a23143.jpg)

![591246bbb9ff31533c890516f97861c](https://user-images.githubusercontent.com/52224629/202463493-b130a6fb-0c93-414e-bd3b-f18a553abaee.jpg)

**Comment by mthierba** [comment]
RC.2 is now available as a stable release: https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-rc.2
