### ISSUE TITLE
-extractFolder in export is not honored

### ISSUE THREAD

**Issue by timker** [pbi-tools/pbi-tools#181]
tested on

windows
pbi-tools.1.0.0-rc.1
pbi-tools.1.0.0-rc.2+preview.4

.\pbi-tools.exe extract '.\reports\SomeReport.pbix' -extractFolder '.\data'

will always place in '.\reports\SomeReport`

**Comment by mthierba** [comment]
Could you enable debug logging and paste the outputs from the command here (https://pbi.tools/cli/#diagnostics)?

The `-extractFolder` option will only be effective for "V3" PBIX files, i.e. files created with a PBI Desktop from September 2020 or newer. Legacy PBIX files have limited support (in PBI Service as well as `pbi-tools`).

**Comment by timker** [comment]
I created a new report, and -extractfolder worked on that

those powerbi files are bound to be older that sept 2020

So it's definitely that

Cheers for the prompt response
