### ISSUE TITLE
questions about versioning of pbi-tools

### ISSUE THREAD

**Issue by TarekSalha** [pbi-tools/pbi-tools#183]
Hi Matthias,
in our company, we are currently discussing to use pbi-tools for our production ci/cd pipe. Still, some of my coworkers are concerned which version to use. Also, we have some questions about wording.
- The RC1 version is the `release` version. Still it hasn't got a lot of features, which are in the later versions. Thus, it can't be feature complete, right?
- all the versions starting from RC1 have `RC` (release candidate?) inside the name. Still, they are marked as `pre-release`, which often relates to experimental code. Are they more like a release candidate (typically well tested) or like a pre-release?
- the latest versions have also the name `preview` in them. What is the difference to the other versions?
- also, there were a couple of breaking changes between the versions. So, what is your approximate timeline for the next official release? (i know, you do this in your spare time :-))

Thanks for answering and best regards,
Tarek

**Comment by mthierba** [comment]
Hi Tarek,
great question - let me clarify.

- `pbi-tools` follows SemVer v2: https://semver.org/
- Each version (1.0, 1.1, 1.2) represents a particular set of features - there are only additions, and no breaking changes, between minor versions.
- The versions already released on GitHub are very conservative: All versions so far have (semantically) been pre-releases of "1.0" - they have not been feature-complete with respect to what "1.0" is supposed to contain. "1.0" will be a thoroughly tested release, supporting full end-to-end extract-compile-deploy workflows for reports and datasets. Currently, there are still some features missing towards that objective, although each release has added additional features. (Check out Orchard Core as another project that remained on 1.0 RC versions for quite a while before the feature-complete 1.0 was released: https://github.com/OrchardCMS/OrchardCore/releases)
- Now coming to the GitHub releases/pre-releases: Each `pbi-tools` GitHub release (1.0-RC.1, 1.0-RC.2, 1.0-RC.3) represents a particular milestone on the way to 1.0. RC.1 introduced the 0.11 extraction schema as well as the docker image (key for CI/CD), RC.2 will complete the Dataset deployment story. *There may or may not be a RC.3, certainly no RC.4.*
- Various RC.2 previews have gone out as GitHub pre-releases: Those introduce new features with fewer guarantees. Pre-releases have been tested less than releases, and implementation details **might** have breaking changes between previews - whilst features are stabilized and mature.
- Pre-releases (previews) are out there specifically to collect feedback and allow users to influence the details around new features. Anyone who wants to be on the bleeding edge, and benefit from the latest features should use the latest pre-release. But should also understand there might be some breaking changes on the way to the next full release. Anyone using a pre-release is also encouraged to actively provide feedback.

There is, obviously, a whole different set of potential breaking changes outside of my control. Those are potential changes to the PBIX format imposed by Microsoft. As you probably know, the MS team has been working on "Desktop Hardening" (https://ssbipolar.com/2021/12/17/tabular-editor-and-desktop-hardening/) behind the scenes. Ultimately, those efforts will definitely bring changes to the PBIX file format, and will allow 3rd party tools like `pbi-tools` to interact with such files much better. However, there are no timelines or details available. `pbi-tools` will of course be in the front row to react to any such changes.

In terms of timelines, I'm currently very busy preparing for a number of conference sessions I'm presenting in September, hence there will be a less direct development work on `pbi-tools` in the next few weeks. Realistically, there will be one or two small further previews in the meantime and a full release around the end of September. But don't quote me on that.

HTH,
Mathias
