### ISSUE TITLE
Option to ignore certain model annotations

### ISSUE THREAD

**Issue by mthierba** [pbi-tools/pbi-tools#19]
`PBI_NavigationStepName` and `PBI_ResultType` (on tables) change frequently or are being re-ordered, leaving noise in commit history.

![image](https://user-images.githubusercontent.com/3763662/119116172-e2fe4800-ba1f-11eb-81fc-16ebc1a963a0.png)

**Comment by ruhrpotter** [comment]
Is this enabled by default when using the most recent rc? Or do I have to enable it for my project? If I need to enable it first, where to do it? I still see "PBI_ResultType" as a change when creating pbit

**Comment by mthierba** [comment]
Hi @ruhrpotter , nothing gets ignored by default. You need to explicitly specify the rules for your project. A practical example is here: https://github.com/pbi-tools/pbi-tools/blob/main/data/Samples/Adventure%20Works%20DW%202020/.pbixproj.json 
I would not recommend to ignore the "PBI_ChangedProperties" annotation at this point. That's currently required by PBI Desktop to support certain tabular properties. Others are fine, though.
As usual, test before you apply any changes in production!
