### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by PBIQueryous** [pbi-tools/pbi-tools#191]
Good afternoon, I hope you are well.

I have followed your instructions to extract a pbix file using the Pbi-tools in a Windows Powershell. However, I can't get past Step 6 in the instructions. I receive the following error. I must be doing something wrong? Could you please help. Any guidance is much appreciated.

<img width="692" alt="image" src="https://user-images.githubusercontent.com/95970959/192099205-4fb3d1f9-b5cf-47e1-ba77-06b5cb582ebf.png">

**Comment by mthierba** [comment]
Hi,
could you also provide the command-line you ran prior to the error? It looks like you're not pointing to a PBIX file, or at least not to a valid one.

Mathias

**Comment by PBIQueryous** [comment]
Thanks Mathias for getting back so swiftly.

Forgive me, I'm new to Powershell shenanigans. Please see below:

*file path:* C:\Users\pbiqu\OneDrive\Documents\PowerBI\_Practice

*command line: *PS C:\Users\pbiqu\OneDrive\Documents\PowerBI\_Practice>
pbi-tools extract ".\AdventureWorks2020.pbix"

[image: image.png]
[image: image.png]

**Comment by mthierba** [comment]
And you're following the tutorial at this step? https://pbi.tools/tutorials/getting-started-cli.html#6-extract-a-pbix-file

Did you [unblock the AdventureWorks.pbix file](https://pbi.tools/tutorials/getting-started-cli.html#2-unblock-the-zip-file) after downloading it? Skipping that step will make it appear corrupted.

**Comment by PBIQueryous** [comment]
That's the correct step yes.

I definitely did unblock and apply in the file properties.
[image: image.png]

I will start from scratch and try it again with another file, and see if
that works.

I will keep your posted. Thanks Mathias, and sorry to bother you on a
Saturday!

**Comment by PBIQueryous** [comment]
Hmm, interesting, when I try to open to PBIX file I get this sensitivity
error: This might explain it, problem is with AdventureWorks File.


[image: image.png]

I 've just tried it again on a different file and it's worked absolutely
fine!

[image: image.png]

Thank you for helping me out Mathias!
