### ISSUE TITLE
unintended changes of annotations in dataset tables

### ISSUE THREAD

**Issue by TarekSalha** [pbi-tools/pbi-tools#193]
We are sometimes experiencing below displayed changes of annotations of tables even, if we did not touch the tabl at all. We suspect, that they have to do something with the UI state of power query, but the switching of these items back and forth is pretty annoying. Is there any possibility to circumvent the problem or do we have to revert these changes always manually?
Unfortuantely, I cannot put the file into gitignore.

![image](https://user-images.githubusercontent.com/25264670/194571898-935792ad-b6fe-4f0a-97e6-b24bfb324fe0.png)

thanks and best regards,
Tarek

**Comment by mthierba** [comment]
Hi @TarekSalha, there is already a mechanism available for this in `pbi-tools`: Within model serialization settings, exclusion and inclusion rules can be defined for annotations. The use case for this is precisely the one you're describing - PBID gets a bit chatty in those annotations sometimes, and a lot of them you can live without any impact on functionality.

This snippet added to your projects's `.pbixproj.json` will completely remove those annotations when serialializing:

```
{
  "settings": {
    "model": {
      "annotations: {
        "exclude: [
          "PBI_NavigationStepName"
        ]
      }
    }
  }
}
```

Run `pbi-tools extract` once you've changed the options, and those annotations will all disappear from your source code. Wildcards are also supported.

The corresponding change set is here: 5d5073922

**Comment by TarekSalha** [comment]
great, this is exactly, what we were missing. Is there any documentation about all the stuff, you can do inside the pbiproj? I mean there is also all the deployment stuff?

**Comment by mthierba** [comment]
> great, this is exactly, what we were missing. Is there any documentation about all the stuff, you can do inside the pbiproj? I mean there is also all the deployment stuff?

I wish there were. Sorry, I have no one helping me with those practical things. Looking for the ["Documentation" tag](https://github.com/pbi-tools/pbi-tools/labels/documentation) might be worthwhile.
