### ISSUE TITLE
Question regarding Power BI Pro Deployments

### ISSUE THREAD

**Issue by TarekSalha** [pbi-tools/pbi-tools#213]
Hi Matthias,
one of our clients is keen on using pbi-tools for their development/deployments but currently, they are only on power bi pro, thus not able to use xmla deployments. Is there a plan to support also standard [REST](https://learn.microsoft.com/en-us/rest/api/power-bi/imports/post-import) pbix deployments in the future?

I do see, that many cool deploy features like parameterization are not supported, if there is a simple upload of the pbix, but just asking :-)

Cheers, Tarek

**Comment by mthierba** [comment]
PBIX uploads via the REST API are already supported by pbi-tools (in fact, that was released even before XMLA deployments). It's the "Report" deployment mode you're looking for (as opposed to "Dataset"). Admittedly, there are few extra features/options available, compared to Dataset/XMLA deployments. Is there anything in particular you're missing?

**Comment by TarekSalha** [comment]
ok, I thought that "report" deployments are only relevant for "thin" reports. Can you confirm, that it works as well for "thick" reports?

**Comment by mthierba** [comment]
It does. The naming might just be confusing. In conjunction with the "File" source type, it'll upload a PBIX to a workspace, no matter if thick or thin .

**Comment by mikemowgli** [comment]
Hi Mathias,
First of all, thank you for this great project. I'd like to jump in this thread to explain what we'd like to achieve: having a pbix binary file in git is too risky because developers will, sooner or later, include data in it. So our plan is to only push to git the files of the (pro) dataset (without any data) and the thin-report, after a pbitools extract, then compile both and deploy to a pro workspace. Is this scenario valid with the current pbitools version?

**Comment by mikemowgli** [comment]
Thank you for clarifying. In our team, pushing a pbix file to git is too risky as it could always contains data. So we look forward for the ability to deploy a pro dataset (either from pbit, or from folder) to Power BI Service with pbitools. We hope it's on the roadmap. We could potentially contribute to that feature is you're interested.

**Comment by mthierba** [comment]
For PBI Pro this will not be possible with pbi-tools. That's because Microsoft doesn't support it. pbi-tools cannot circumvent Pro/Premium licensing limitations. Of you need to deploy datasets from sources your only options are Premium/PPU/AAS. Unless Microsoft makes any changes here, I cannot.

**Comment by TarekSalha** [comment]
I am not speaking for MSFT here, but as a gold partner I can at least confirm, that to my knowledge MSFT has currently no plans to enable this type of deployment in the near future. @mikemowgli hope, you are not too dissatisfied, but you are certainly not the only one suffering from this lack. :-)
here are 2 thoughts from my projects:
you may still use git in conjunction with `pbi-tools extract` to keep the source code at least for change tracking and deploy with manual steps instead of fully automated.

Also, you could buy a single PPU license and change the workspace at deployment time from pro to premium. this will enable the XMLA endpoint and thus also your desired automated git deployment. Downside: you need maintenance slots, because during deployment (workspace is Premium) your users will not have access to the reports

**Comment by TarekSalha** [comment]
> It does. The naming might just be confusing. In conjunction with the "File" source type, it'll upload a PBIX to a workspace, no matter if thick or thin .

is there some documentation or hint, where to find the suitable config options for this type of deployment? e.g. are parameter settings valid? This would be really helpful to minimize deployment errors

**Comment by mthierba** [comment]
> > It does. The naming might just be confusing. In conjunction with the "File" source type, it'll upload a PBIX to a workspace, no matter if thick or thin .
> 
> is there some documentation or hint, where to find the suitable config options for this type of deployment? e.g. are parameter settings valid? This would be really helpful to minimize deployment errors

Here's an official demo project using the `Report` deployment mode: https://github.com/pbi-tools/report-devops-demo/blob/main/.pbixproj.json

# List of supported manifest settings for Report/Upload deployments

| Property/Object | Notes |
| --- | --- |
| manifest.authentication | Sets deployment credentials. Only service principal is supported. |
| manifest.options.import.nameConflict | Determines the behavior in case a report/dataset with the same name already exists. Default is `CreateOrOverwrite`. [Other available options](https://learn.microsoft.com/rest/api/power-bi/imports/post-import-in-group#importconflicthandlermode) |
| manifest.options.import.skipReport | Determines whether to skip report import, and import the dataset only. [Reference](https://learn.microsoft.com/rest/api/power-bi/imports/post-import-in-group#uri-parameters) |
| manifest.options.import.overrideReportLabel | Determines whether to override existing label on report during republish of PBIX file, service default value is true. [Reference](https://learn.microsoft.com/rest/api/power-bi/imports/post-import-in-group#uri-parameters) |
| manifest.options.import.overrideModelLabel | Determines whether to override existing label on model during republish of PBIX file, service default value is true. [Reference](https://learn.microsoft.com/rest/api/power-bi/imports/post-import-in-group#uri-parameters) |
| manifest.options.pbiBaseUri | Allows setting an alternative Power BI base uri, supporting different Azure Clouds (default: 'https://api.powerbi.com'). |
| manifest.options.tempDir | Allows setting an alternative temp folder into which .pbix files are compiled. Supports variable expansion (default: [`System.IO.Path.GetTempPath()`](https://learn.microsoft.com/dotnet/api/system.io.path.gettemppath)). |
| environment.displayName | For PBIX import deployments, corresponds to the `datasetDisplayName` API parameter. Must include a file extension. For dataset deployments, sets the dataset name shown in Power BI Service. Defaults to the source file/folder name if not specified in the manifest. Supports parameter expansion. [Reference](https://learn.microsoft.com/rest/api/power-bi/imports/post-import-in-group#uri-parameters) |
| environment.workspace | A workspace name or guid. Supports parameter expansion. |

As you can see from the above, currently only `displayName`, `workspace`, and `pbiBaseUri` support parameter expansion, i.e. allow injecting values from _manifest.parameters_.

**Comment by mthierba** [comment]
Did the question get answered, can this issue be closed?

**Comment by TarekSalha** [comment]
Hi Mathias, sorry for the late answer. Yes, this statement clarified the current possible options a lot. Obviously, xmla deployment is way more powerful, but for customers not willing to spend the money, this is at least a good possibility to automate SOME stuff.
