### ISSUE TITLE
Some versions are not supported

### ISSUE THREAD

**Issue by jiaopengzi** [pbi-tools/pbi-tools#214]
Hi @mthierba 

I was in the time when I had the extraction function
e.g.
```
pbi-tools extract -pbixPath "C:\desktop\test.pbix" -extractFolder C:\desktop\folder
```
Extracted files are not extracted to the corresponding folder according to my setting `C:\desktop\folder`
Instead, create a new folder in the same directory as `C:\desktop\test.pbix` for extraction.

And the extracted file cannot be compiled, and the error is reported as follows when compiling
```
pbi-tools compile -folder " C:\desktop\test" -format PBIT -outPath "C:\desktop\test.pbit" -overwrite true
Reading PBIXPROJ settings from: C:\desktop\test\.pbixproj.json
An unhandled exception occurred.
System.NotSupportedException: The PBIX file/project does not contain a V3 model. This API only supports the V3 PBIX format.
   在 PbiTools.Model.PbixModel.EnsureV3Model() 位置 X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Model\PbixModel.cs:行号 88
   在 PbiTools.Model.PbixModel.FromFolder(String path) 位置 X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Model\PbixModel.cs:行号 202
   在 PbiTools.Cli.CmdLineActions.CompilePbix(String folder, String outPath, PbiFileFormat format, Boolean overwrite) 位置 X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Cli\Compile.cs:行号 70
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 PowerArgs.ArgAction.Invoke()
   在 PbiTools.Program.Main(String[] args) 位置 X:\pbi-tools\BRANCHES\1.0.0-rc.1\src\PBI-Tools\Program.cs:行号 94

```

The above are some of the problems that occur in older versions.

Just save it with a new version(Power BI Desktop 2022.10), it seems that the problem is solved.

In addition, my secondary development of pbi-utils(https://github.com/jiaopengzi/pbi-utils) has been released, thank you very much.

**Comment by mthierba** [comment]
That's correct. Legacy files (produced with very old versions of PBI Desktop) aren't supported. But Microsoft doesn't support those either - AFAIK, they only go two releases back. Official policy is to always stay on the latest version of Desktop.
