### ISSUE TITLE
Parameters in Info table for Github Deployment not updating

### ISSUE THREAD

**Issue by jeanniemaclachlan** [pbi-tools/pbi-tools#217]
Hi Mathias, 

I followed the instructions in the Release Note for adding Info table for deployment. 
However, the parameters were not replaced when deployment github action ran. 

What I did:
1. Add info table with power query that is in the Contoso pbix in this repo: https://github.com/pbi-tools/dataset-devops-demo
2. Created parameters needed
3. Created the measures to expose the parameter values. 
4. Added parameters and enabled dataset>replaceParameters = true, in the deployment manifest according to: https://github.com/pbi-tools/dataset-devops-demo/blob/main/.pbixproj.json

But when the development deployment ran, the values are still showing the default values instead of being replaced during deployment. 
Am I missing something?

Thank you!

**Comment by mthierba** [comment]
Which release/version of pbi-tools are you using? Parameter support was only added in the latest releases. Did you look at the deployment logs? The parameter transformations are added to the outputs in detail. It'll give you all the details. Note that only "dataset" deployments support parameter replacements.

**Comment by jeanniemaclachlan** [comment]
Hi Mathias, 

Thanks for getting back to me. 

I am deploying a dataset and using: 1.0.0-rc.2+preview.6 on desktop and the dockerized version used in github action is also the latest
<img width="542" alt="Screen Shot 2022-12-21 at 6 49 05 AM" src="https://user-images.githubusercontent.com/87496916/208932974-118e9395-1db0-4e37-adef-4a5f7117d756.png">

Below is the parameter I added in the github manifest 
<img width="472" alt="Screen Shot 2022-12-21 at 9 24 47 AM" src="https://user-images.githubusercontent.com/87496916/208966677-5d628f7e-e266-4fb8-899c-807d6a730409.png">


When running `pbi-tools deploy ... -watch` on local, I do see the Parameters in the output:
<img width="749" alt="Screen Shot 2022-12-21 at 9 25 47 AM" src="https://user-images.githubusercontent.com/87496916/208967177-2d74aca5-f26c-4c2a-8585-c5e8a1d21373.png">

But when running through deployment in Github Action, there is no Parameter 
<img width="927" alt="Screen Shot 2022-12-21 at 8 34 55 AM" src="https://user-images.githubusercontent.com/87496916/208967331-fe6ee3ea-d531-4cb3-92c8-724dc90792cf.png">
updating section:

**Comment by mthierba** [comment]
The `dataset` config settings are nested inside _manifest.options_. Your screenshot shows it at the same level as _parameters_. Please refer to the example here: https://github.com/pbi-tools/dataset-devops-demo/blob/main/.pbixproj.json

```json
{
  "version": "0.12",
  "deployments": {
    "Contoso": {
      "mode": "Dataset",
      "options": {
        "dataset": {
          "replaceParameters": true,
          "deployEmbeddedReport": true
        }
      },
      "parameters": {
      },
      "environments": {
      }
    }
  }
}
```

**Comment by jeanniemaclachlan** [comment]
I'm so sorry I completely missed this.. I looked at it so many times and it didn't throw an error so thought it was working.
Thank you so much!  It works now!  Happy Holidays :)
