### ISSUE TITLE
Allow DBUP ExecutionTimeout to be set

### ISSUE THREAD

**Issue by jakeduddy** [pbi-tools/pbi-tools#233]
"Connection Timeout" can be set for connection setting to SQL server but DBUP has a default timeout of 30s, which doesn't seem to be adjustable with PBI-Tools. A parameter to be sent from `.pbixproj.json` would allow more complex scripts to be executed.

https://github.com/pbi-tools/pbi-tools/blob/main/src/PBI-Tools/Deployments/SqlScriptsDeployer.cs
Function: BuildUpgradeEngine + `engineBuilder.WithExecutionTimeout(TimeSpan.FromMinutes(5));`

**Comment by mthierba** [comment]
The `Microsoft .Data.SqlClient` _Command Timeout_ connection string property (https://github.com/dotnet/SqlClient/blob/2c2f100d8ab9a1f6ee8c048a260d77e6a738e1e7/release-notes/2.1/2.1.0-preview2.md#command-timeout-connection-string-property) does not do the job?
In dbup, the timeout is only overwritten if specified, other the underlying provider's timeout kicks in, I believe: https://github.com/DbUp/DbUp/blob/cc439e28add976c057d680c903b80e089d288c7a/src/dbup-core/Support/ScriptExecutor.cs#L131

**Comment by jakeduddy** [comment]
"Command Timeout" does indeed work, was using "Connection Timeout"

**Comment by mthierba** [comment]
ref: dotnet/SqlClient#722
