### ISSUE TITLE
"Invalid Report" error after deployment when accessing from Power BI Home's "Recommended" list

### ISSUE THREAD

**Issue by hcmjensen** [pbi-tools/pbi-tools#234]
Hi, Mathias.  Last night I deployed into a production workspace for the first time using pbi-tools and Github actions with a Power BI deployment pipeline (very exciting!).  This is a workspace that preexisted its pipeline, and I wanted the URLs for reports to work, so artifact IDs could not change (some of them are embedded into other applications that reference their IDs).  I deployed the production workspace backwards into Test and Development workspaces, and then deployed my dataset and report changes in the reverse direction.  Everything tested fine for me and IDs and URLs had not changed, but this morning many users (but not all) are reporting that they get the following error when they try to access the report from Power BI's Home screen, under "Recommended":

"Invalid Report: There is no dataset associated with this report"

This error is a red herring; there most definitely is a dataset associated with the report.  I'm guessing that something is cached in the browser, but even after having the user clear their cache and cookies, the Power BI Home link still gets the above error.  A workaround is to have them go to the direct URL for the report after clearing cache and cookies (before clearing, the URL gets the same error).  Any idea what is going on here?  I'd love to avoid this if possible since it will be a real headache if it occurs every time we use pbi-tools to deploy and I don't want any barriers to adoption on my team.

Many thanks,
Hannah

**Comment by mthierba** [comment]
Hi @hcmjensen, `pbi-tools` does not interact with [PBI Deployment Pipelines](https://learn.microsoft.com/en-us/power-bi/create-reports/deployment-pipelines-overview) at all, and both are mutually exclusive deployment options. Could you clarify what "using pbi-tools and Github actions with a Power BI deployment pipeline" means?

**Comment by hcmjensen** [comment]
Sure.  I used Github actions and pbi-tools to deploy into the development workspace, which is the first workspace in my Power BI deployment pipeline.  Then I used the pipeline deployment functionality to move from development to test to production.

**Comment by mthierba** [comment]
Sounds like this is not related to what `pbi-tools` does. Which is basically just to automate the upload of a .PBIX file using Microsoft's public APIs. Is this behavior reproducible?

**Comment by hcmjensen** [comment]
Sadly, I have not been able to reproduce it with any test accounts yet.  The only thing that seems to solve the problem is giving the user view access to the workspace in which the report is located.  Then the no dataset error disappears and the report works fine.  But you're right, I don't believe this has anything to do with pbi-tools.  If I'm able to reproduce the issue at some point, I will open a ticket with Microsoft.  Thanks, Mathias!
