### ISSUE TITLE
Unauthorized access exception

### ISSUE THREAD

**Issue by derik-roby** [pbi-tools/pbi-tools#236]
When extracting pbix file to a git enabled folder, pbi-tools extract command is trying to remove files inside .git folder.
Please advise if I am doing any steps wrong. 

![grafik](https://user-images.githubusercontent.com/122028333/214610687-4689de85-fa22-479b-b676-3c26b2b1bfb7.png)

**Comment by mthierba** [comment]
The general practice here would be not to directly extract into a git-enabled folder, and instead to use a sub-folder. That allows a clean separation between PBIX source files and other project-level files (`README`, `.git`, `.gitignore`, etc).

**Comment by derik-roby** [comment]
Thanks for the advice. And thanks for the tool and making it public.
