### ISSUE TITLE
Replacing model with a connection - Get un-handleable exception: pbi-tools.exe - Assert Failure

### ISSUE THREAD

**Issue by andy-clapham** [pbi-tools/pbi-tools#237]
I've written a little script that takes a large multi-tabbed report and
1 - removes the Model folder
2 - copies a connections.json that defines a linked dataset to the original data on the PBI service.
3 - sets all but a few of the tab sections to visibility:0
3 - compiles the pbix.

This works great, and enables us to provide a subset view of the main report to different workspaces with access defined by role - a huge timesaver!

However, while compiling the pbix I get a unhandleable windows assert exception from somewhere ... probably deep within .net itself:
![image](https://user-images.githubusercontent.com/67688959/214616735-2701a78d-6743-45c1-9649-a2ebe73e8df0.png)

While it's not a showstopper as ignoring it works fine, it does mean I can't fully automate this generation.
Any suggestions as to why this is happening, or if there's anything I can do?

**Comment by mthierba** [comment]
I've had this, too, recently. Need to investigate further.

Immediate workaround for you would be to compile with the Core (x-platform) edition instead (available for both .Net6 and .Net7) - but retain the Desktop edition for 'extract' - both can live in the same folder as they don't share any files. There's definitely no issue with that one as it uses a completely different implementation for 'compile' (which I may well port to the Desktop version now).

**Comment by andy-clapham** [comment]
Fantastic, that worked. Yay can finally update all the departmental reports with one command!
