### ISSUE TITLE
pbi-tools extract --File Not Found

### ISSUE THREAD

**Issue by cww2021** [pbi-tools/pbi-tools#242]
I was following the tutorial instructions until step 6, when I tried to extract the file, it says file not found. Did I do anything wrong?

<img width="948" alt="Capture" src="https://user-images.githubusercontent.com/90115585/220460519-ca19849b-cf19-4660-815d-a6b59adae100.PNG">

**Comment by mthierba** [comment]
The path was not passed correctly to the tool by your shell - it complains about not finding `.\Adventure`. 

Please try double-quotes: `pbi-tools extract ".\Adventure Works DW 2020.pbix"`. Also ensure that pbix file exists in the current folder.

**Comment by cww2021** [comment]
> 
Thank you for prompt reply Mathias, I used double-quotes and it fixed the issue. Could you please update the tutorial info because it has single-quote in there? Thanks!
![image](https://user-images.githubusercontent.com/90115585/220471442-c994692e-a725-497b-a55d-dc7bd6ac7cc7.png)

**Comment by mthierba** [comment]
The tutorial was recorded using PowerShell, where this is valid syntax. I can swap the delimiters to make it more generic.

**Comment by mthierba** [comment]
Updated the tutorial to make it more robust. Thanks for reporting!

![image](https://user-images.githubusercontent.com/3763662/220547465-c945cf95-479e-43d5-9b4f-9d1d4a50d1e2.png)
