### ISSUE TITLE
dataAccessOptions: Indented struct body expected.

### ISSUE THREAD

**Issue by bcdobbs** [pbi-tools/pbi-tools#265]
Hi,
Loving TMDL. I've just setup my first github action to deploy a model. Thank you!

I did however come across the following issue.
First I converted my existing model.bim to TMDL folder:
`pbi-tools convert model.bim`

Then when I tried to deploy it threw the following error:
> An unhandled exception occurred during deserialization. 
> TMDL Format Error: [Indentation] Indented struct body expected.
> Path:        [C:\Source\TrustDW-Models-DeploymentTest\Finance\model.tmd]
> Line Number: 6
> Text:          defaultPowerBIDataSourceVersion: PowerBI_V3

I found that in model.tmd there was:
`	culture: en-GB`
`	dataAccessOptions:`
`	defaultPowerBIDataSourceVersion: PowerBI_V3`
`	discourageImplicitMeasures`

Removing the dataAccessOptions: line solved the problem.

Not sure if this is a problem with my original model.bim file.

**Comment by mthierba** [comment]
Thanks for reporting. This would indeed fail the TMDL parser. Would you be able to share just the top bit of your BIM - including the `dataAccessOptions`? I'd like to understand how that converted to the output you posted.

**Comment by bcdobbs** [comment]
Hope this is what you need. Let me know if you want the full .bim file.

```  
"model": {
    "name": "Finance",
    "description": "Analytics model using data from PSF.",
    "culture": "en-GB",
    "dataAccessOptions": {
      "legacyRedirects": false,
      "returnErrorValuesAsNull": false
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-GB"
...
```

Thank you again.

**Comment by mthierba** [comment]
That's perfect. Thanks!

**Comment by mthierba** [comment]
Fixed in TMDL Preview-2, which is included in https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-rc.4
