### ISSUE TITLE
Some questions about `.tmd`

### ISSUE THREAD

**Issue by jiaopengzi** [pbi-tools/pbi-tools#266]
Hello, 

I have noticed that in the latest version `1.0.0-rc.3 (TMDL Preview-1)` of the extracted model, the format of the files has changed from `.json` in previous versions to `.tmd`. 
Additionally, there have been significant changes in the folder structure.

Based on the previous version `1.0.0-rc.2`, I have developed some small tools for `pbi-utils`. However, I am not familiar with the new structure and would like to know how to compare and learn from these `.tmd` files.

Thank you very much.

![image](https://user-images.githubusercontent.com/52224629/231726461-1e6b81a5-879e-47fb-90f3-5a9017977d2f.png)

**Comment by jiaopengzi** [comment]
> Hello, https://learn.microsoft.com/en-us/analysis-services/tmdl/tmdl-overview?view=asallproducts-allversions

thanks, I got it.

Another question, is the tmdl extension of vscode still open? I can't find it after searching.

**Comment by didierterrien** [comment]
Hello,
I don't think the VS Code extension is available. Mathias tweeted recently about a VS Code event. Maybe there will be some announcement soon

**Comment by jakeduddy** [comment]
If you want to keep the json structure, as you have existing tooling, you can specify the extract to use legacy mode. Just use pbi-tools help to check though the options
