### ISSUE TITLE
Question: TMDL like support for Report sections

### ISSUE THREAD

**Issue by claywey** [pbi-tools/pbi-tools#268]
TMDL has been great on the data model side of things, but it doesn't resolve the problems with the Report's extraction. In my use case, the "Report" folder has 66,000 lines of code across 500+ files. In particular, it is on the Report side where we need version control the most. Is there work being done to bring some TMDL like to the Report as well?

**Comment by andy-clapham** [comment]
Absolutely agree.

The data model was always the least of my problems, it's always been quite well organised in the pbix.

However ... Reports, tabs and bookmarks ... Oh my! Add one extra component to a report, or moving a tab, and diff+merge is totally impossible. I resort to cut and paste in the UI itself here, which is not a scalable practice. Funny how RDL got to the point where it worked ok in VCS. But power bi didn't build on the learning from this.

I have seriously considered working out a round-trippable language on my own here, so I'd love to hear any inside knowledge people have on the status of the reports equivalent of tmdl.

**Comment by mthierba** [comment]
I can share this is being worked on by Microsoft, but so far with no publicised timelines. Would recommend reaching out to @RuiRomano as that falls into his remit.

**Comment by andy-clapham** [comment]
Thanks Mathias!
