### ISSUE TITLE
Planning and feasibility to switch the "deploy" from XMLA to REST API only

### ISSUE THREAD

**Issue by 9pr19** [pbi-tools/pbi-tools#271]
Hello @mthierba ,

pbi-tools is a life saver tool, thank you for all your work.

As far as I understand the only way to deploy a pbixproj to Power BI service - in my use case it’s a "thick report" - is to use XMLA protocol. Unfortunately XLMA is available only for Premium capacity Workspace (PPU or Capacity).

I currently can’t assign a Premium capacity to all Workspaces nor PPU license to all users.

After reading the code I guess that Dataset deployment and Refresh need XMLA but Report deployment is done with REST API?
I guess refreshing a Dataset with REST API would not be a big deal for me to implement in my CI/CD script after calling pbi-tools deploy. But it still remains the Dataset deployment.
It seems you are using online «Analysis Services» to compile dataset... would it be possible to either use a dedicated workspace (with a premium capacity) to do the compilation and then use REST API to deploy those objects to another workspace (without license). Or host locally some kind of Analysis service for the compilation?

Another idea would be to assign temporarily to a Workspace a PPU or Premium capacity, do the deployment then remove the Premium license then trigger with REST API the Dataset refresh (changing the capacity reset the dataset data). It seems a terrible idea.

Do you have any plan to implement REST API only deploy functionality to Power BI service - at least for dataset?
In the meantime, is it possible to bypass that limitation of pbi-tools and publish a pbixproj with REST API only?

Thank you very much

**Comment by mthierba** [comment]
pbi-tools will not implement any "hacks" that circumvent Pro/Premium licensing restrictions.

You can already use `pbi-tools deploy` today for thick reports into Pro by providing the full PBIX file (in conjunction with the "Report" deployment mode). There is no API to deploy a dataset from BIM/TMDL sources into Pro. You'll need to lobby Microsoft to make that available.

For dataset refreshes, however, the REST API would be a viable alternative to the current XMLA method. I'll need to find funding to implement that option, though.

**Comment by 9pr19** [comment]
Sorry the the way I expressed myself, the point wasn’t to circumvent or hack licensing restrictions. My point was more whether these functionalities are available through other means than XMLA like Ghaph REST API or some other technics I’m not aware of. I’m digging around and try to probe the boundaries of different solutions and assess the need in terms of licensing. 

I’m very fond of the pbixproj solution because you can dissociate the data from the code (model, report) and do versioning... Continuous Deployment of PBIX imply that you are storing and deploying data AND code altogether - I do no like that perspective.

Currently pbi-tools cannot compile pbixproj to PBIX (I do not know whether this is a functionality that you are planning to implement) and it’s not possible to deploy a PBIT (model+report) directly to Power BI service (as far as I know).

I guess I will end up with the Continuous Deployment of PBIX and hope Microsoft do something to publish a model with something else than XMLA or open XMLA to other levels of licensing.

Thank you for you work and your help @mthierba 
I will keep an eye of the evolution of your work in this repository.
