### ISSUE TITLE
Limitations deserialising TMDL to the desktop

### ISSUE THREAD

**Issue by didierterrien** [pbi-tools/pbi-tools#275]
Hi Mathias,
When deserialising TMDL to the desktop, I noticed some limitations like the impossibility to update M queries. Updating DAX code works very well.
Those limitations look like XMLA endpoint ones.

- Do you confirm XMLA endpoint is used by TOM.TmdlSerializer ?

- Can you share if some evolutions concerning these limitations are in the TMDL roadmap ?

- Is there a possibility for TOM.TmdlSerializer.DeserializeModel to report some updates failed ?

Thanks a lot in advance

**Comment by mthierba** [comment]
When you're saying "deserializing to Desktop", I'm assuming you're talking about `pbi-tools compile`? Remember that that's currently unsupported, so you're using it at your own risk: https://pbi.tools/cli/supported-features.html

TMDL and the Tmdl serializer are client-side Features only, the XMLA endpoint is not involved here. Unless I'm misunderstanding your question?

Some specifics would help in terms of what's failing for you.

**Comment by didierterrien** [comment]
Sorry, I hope to be precise enough now
A .Net application is connected to Power BI desktop through SSAS local instance like many external tools do (DAX Studio, Tabular Editor, ...). This doesn't involve PBI tools.

1. TOM.TmdlSerializer.SerializeModel exports TMDL files correctly
2. TMDL files are modified in VS Code (very simple modifications)
3. TOM.TmdlSerializer.DeserializeModel imports TMDL files without error but modifications made in M code are not imported while modifications made in DAX code are imported

**Comment by mthierba** [comment]
Ah, understood. The deserialization completes without errors, though? There are no known limitations with respect to M expressions (partition queries or shared expressions). Could you share the files that don't import correctly, possibly even the .Net code you use to update the model? There may well be an issue with the latter. How did you confirm the outcome of the change? Did you view the model in Tabular Editor?

**Comment by didierterrien** [comment]
There is no error returned
Here is the code:

```
public void Model_to_TMDL(string Folder)
    {
        try
        {
            TOM.TmdlSerializer.SerializeModel(SSAS_model, Folder + @"\1.3 - TMDL --------");
        }
        catch (Exception ex)
        {
            Debug_print("Model to TMDL error : " + ex.Message);
        }
    }
```

```
    public string TMDL_to_model()
    {
        try
        {
            var Imported_model = TOM.TmdlSerializer.DeserializeModel(Project_folder + Model_folder + @"\1.3 - TMDL --------");
            Imported_model.CopyTo(SSAS_database.Model);
            SSAS_model.SaveChanges();
            return "";
        }

        catch (TOM.Tmdl.TmdlFormatException ex)
        {
            return Constants.vbCrLf + ex.Message + Constants.vbCrLf + "     Path : " + ex.Path + Constants.vbCrLf + "     Line : " + ex.LineNumber + "   " + Constants.vbTab + ex.LineText;
        }
        catch (Exception ex)
        {
            return  ex.Message;
        }
    }
```


Here is a very simple pbix test file:
[Simple test report.pbix.zip](https://github.com/pbi-tools/pbi-tools/files/11303817/Simple.test.report.pbix.zip)

That's the TMDL file I get:
[Test table.tmd.zip](https://github.com/pbi-tools/pbi-tools/files/11303820/Test.table.tmd.zip)

If I modify these strings, the measure is updated in the desktop and in TE but the column is updated only in TE. When I apply changes in the desktop, the column reverts to its previous value in the desktop and TE:
![image](https://user-images.githubusercontent.com/37301981/233842281-f3dcc39f-96b2-409f-8e43-cbd3f8155992.png)

The tool is available here (TMDL bridge):
[https://github.com/didierterrien/Power-BI-Sidetools/releases/tag/V1.3.2-test](https://github.com/didierterrien/Power-BI-Sidetools/releases/tag/V1.3.2-test)

![image](https://user-images.githubusercontent.com/37301981/233843269-0f5d915d-d7d3-4d9d-a1e6-3a3051293ca7.png)

**Comment by mthierba** [comment]
So you're making a connection to the local port of a PBI Desktop model? Please be aware that only certain types of modifications are currently possible in that scenario: https://docs.tabulareditor.com/te3/desktop-limitations.html None of that changes because of TMDL.
