### ISSUE TITLE
Regarding converting PBIX to PBIT 

### ISSUE THREAD

**Issue by Gayatri-khatale** [pbi-tools/pbi-tools#286]
Hi, Good morning. Actually i want to convert powerbi PBIX files to PBIT files which all are reside in one folder. I am trying to use PBI-Tools for this task. But I am facing failure. So can you please tell me the steps how should I do this?
Thank you!

**Comment by mthierba** [comment]
Could you please explain what you've tried so far and which errors you've encountered?

**Comment by Gayatri-khatale** [comment]
Thank you for your reply. I have already resolved the issue. Once again Thank you!
________________________________
