### ISSUE TITLE
How to create PBIP folder from a PBIT

### ISSUE THREAD

**Issue by mukeshKumarFabric** [pbi-tools/pbi-tools#287]
Hi Mathias,

Appreciate your work with PBI tools. It helped us so far.

Given the Microsoft launched the PBIP project folder with GIT integration, can you please let us know if we can use PBI tools to convert PBIT to PBIP folder?
and also, if we can compile back from PBIP to PBIX to deploy.

Thank you.

**Comment by mthierba** [comment]
That is planned for an upcoming release in June.

**Comment by mukeshKumarFabric** [comment]
Great. Thank you Mathias. Waiting for the release.

**Comment by mertbakir** [comment]
Any news on this and would it be possible to convert pbit to pbix? I didn't want to open a new issue.

Let's say I have some pbit files, I want to define the parameters for each of them in a yaml file and convert them into pbix files programmatically.

**Comment by mukeshKumarFabric** [comment]
Hi @mthierba  just checking when can we expect PBI tools to support PBIP project folder to PBIT/PBIX  conversion and vice versa ?
