### ISSUE TITLE
Future of pbi-tools following PBIT file format and Git with Azure DevOps functionnality

### ISSUE THREAD

**Issue by 9pr19** [pbi-tools/pbi-tools#294]
Hello @mthierba,

I’m wondering following the new functionalities delivered recently by Microsoft (PBIT and Git with Azure DevOps) whether you will continue to maintain and add new functionalities to pbi-tools?

Thank you very much :)

**Comment by mthierba** [comment]
Yes, absolutely. The investments into the future of `pbi-tools` will be going up, with a commitment to maintain the free and open-source version. You can expect some significant announcements in that space in the next couple of months.

**Comment by 9pr19** [comment]
It’s an excellent news ... I can’t wait these announcements.
And thank you for your hard work.
