### ISSUE TITLE
Exclusion/inclusion annotation in TMDL

### ISSUE THREAD

**Issue by d-cegielka** [pbi-tools/pbi-tools#296]
Should/will annotation exclusion/inclusion work with TMDL serialization mode? #19 
I tested the extract/convert of the project with the config below
```
{
  "version": "0.13",
  "created": "2023-07-03T09:42:03.8081015+00:00",
  "lastModified": "2023-07-31T15:05:01.4041593+02:00",
  "settings": {
    "model": {
      "serializationMode": "Default",
      "annotations": {
        "exclude": [
          "PBI_NavigationStepName"
        ]
      }
    }
  }
}
```
but in the .tmd file of the table there is an annotation that adds unwanted changes.
```
	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

	changedProperty = IsHidden

```

**Comment by mthierba** [comment]
Good observation - those currently are only applied to the legacy (PbixProj) format. But there's no reason why it shouldn't apply to TMDL. Will add this to a future release.
