### ISSUE TITLE
Cloud Credentials - Invalid credentials

### ISSUE THREAD

**Issue by jakeduddy** [pbi-tools/pbi-tools#297]
Getting the following error 

`(Failed to save modifications to the server. Error returned: '<ccon>The credentials provided for the AnalysisServices source are invalid. (Source at powerbi://api.powerbi.com/v1.0/myorg/datasets;FinCube.)`

Service Principal is a Member in both the Deployment and Data Soruce workspaces, plus has all permissions in the datasource database.

```json
"credentials": [
        {
          "match": {
            "datasourceType": "AnalysisServices",
            "connectionDetails": {
              "server": "powerbi://api.powerbi.com/v1.0/myorg/Datasets",
              "database": "FinCube"
            }
          },
          "type": "OAuth2",
          "updateMode": "BeforeRefresh",
          "useDeploymentToken": true
        }
      ]
```

**Comment by mthierba** [comment]
Does this fail straight away or only after a long-running deployment? The token used expires after 1 hr - just ruling this one out first.

**Comment by mthierba** [comment]
You seem to be missing `options.dataset.setCredentials = true` in your manifest. Looking at the logs, the credentials step is being skipped completely.

```json
      "options": {
        "dataset": {
          "replaceParameters": true,
          "setCredentials": true
        }
      },
```

**Comment by jakeduddy** [comment]
That was it, that part was not mentioned in the [1.0.0-rc.3 (TMDL Preview-1)](https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-rc.3) release notes. But now you mention it I do see it in [incremental-refresh-demo](https://github.com/pbi-tools/incremental-refresh-demo/tree/main)
