### ISSUE TITLE
Possible to deploy datasets via API to Power BI Pro workspace?

### ISSUE THREAD

**Issue by julian-wendt** [pbi-tools/pbi-tools#300]
Hi Matthias,

many thanks for this great product. I have one question: Will there be the chance that we can deploy datasets only via API with the ability to change PQ params before?

Background: We are developing a report having one shared dataset in a dedicated workspace which is consumed by different thin reports in multiple workspaces dedicated to customers. The reports are filtered which is done by changing JSON files before compiling/deploying reports but it feels not fully secure. To improve security we would like to stop sharing a single dataset to different customers but provide one dataset per customer report which data sources are then filtered via PowerQuery ...

Also we are thinking about update rings which also would require different datasets.

We do not have Power BI Premium and I don't believe we will have in future so XMLA is not available to me and my team ...

Would be great to have this covered in future but I understand that this could be really hard to implement.

Kind regards and many thanks,
Julian

**Comment by julian-wendt** [comment]
@mthierba any idea on this?

**Comment by mthierba** [comment]
For Pro workspaces, the only option you currently have is to deploy a PBIX file containing your model. Note that pbi-tools will not be able to compile those, hence you'd need to version-control the binary files.

**Comment by jambarnes-fi** [comment]
I see this issue is still open, so i assume this is still the case as of today (11/21/2023), right?

**Comment by mthierba** [comment]
> I see this issue is still open, so i assume this is still the case as of today (11/21/2023), right?

Correct. Automated deployment options to Power BI Pro are _very_ limited. The only (Microsoft) supported option is an upload via PBIX files.

**Comment by jambarnes-fi** [comment]
> > I see this issue is still open, so i assume this is still the case as of today (11/21/2023), right?
> 
> Correct. Automated deployment options to Power BI Pro are _very_ limited. The only (Microsoft) supported option is an upload via PBIX files.

I am confused then as I thought you demonstrated in your Intro to TMDL video on YouTube that this was in fact working, and noted that this was not a PBI-Tools feature, per se, but that all PBI-Tools was doing was calling the Deserialize methos that was recently added to the TOM library.  What did I get wrong there?

**Comment by mthierba** [comment]
> > > I see this issue is still open, so i assume this is still the case as of today (11/21/2023), right?
> > 
> > Correct. Automated deployment options to Power BI Pro are _very_ limited. The only (Microsoft) supported option is an upload via PBIX files.
> 
> I am confused then as I thought you demonstrated in your Intro to TMDL video on YouTube that this was in fact working, and noted that this was not a PBI-Tools feature, per se, but that all PBI-Tools was doing was calling the Deserialize methos that was recently added to the TOM library.  What did I get wrong there?

This is a licensing restriction that applies to Pro/Shared workspaces. TMDL is a new serialisation format, but it does not change the licensing. All automated deployment features for datasets (via API or Fabric Git Integration) require Premium.

What was asked for in the original question is certainly possible today, but not in Power BI Pro. (And probably never will.)

**Comment by jambarnes-fi** [comment]
> > > > I see this issue is still open, so i assume this is still the case as of today (11/21/2023), right?
> > > 
> > > 
> > > Correct. Automated deployment options to Power BI Pro are _very_ limited. The only (Microsoft) supported option is an upload via PBIX files.
> > 
> > 
> > I am confused then as I thought you demonstrated in your Intro to TMDL video on YouTube that this was in fact working, and noted that this was not a PBI-Tools feature, per se, but that all PBI-Tools was doing was calling the Deserialize methos that was recently added to the TOM library.  What did I get wrong there?
> 
> This is a licensing restriction that applies to Pro/Shared workspaces. TMDL is a new serialisation format, but it does not change the licensing. All automated deployment features for datasets (via API or Fabric Git Integration) require Premium.
> 
> What was asked for in the original question is certainly possible today, but not in Power BI Pro. (And probably never will.)

Ah, gotcha.  Sorry for not reading the prior question more carefully and causing confusion.  We have Power BI Premium.  So we can do automated deploys to that endpoint then?  Thanks for your replies!  I have high hopes here.
