### ISSUE TITLE
pbi-tools extract

### ISSUE THREAD

**Issue by Amirmoosavi2006** [pbi-tools/pbi-tools#302]
I download pbi-tools.1.0.0-rc.4 from github. when i want to extract pbix file an unhandled exception occurred.
this says: Microsoft.PowerBI.Packaging.Storage.NewerFileVersionException: '1.28' is newer than the product version.
can any one help me please?

**Comment by mthierba** [comment]
@Amirmoosavi2006 That sounds like you're using an out-of-date version of Power BI Desktop on your machine. Would you mind posting the output of `pbi-tools info` here for further details?

**Comment by Amirmoosavi2006** [comment]
tanks a lot.
