### ISSUE TITLE
translation metadata is lost

### ISSUE THREAD

**Issue by mertbakir** [pbi-tools/pbi-tools#304]
It looks like we lose the translation metadata on the model when using extract then compile.

**Comment by mthierba** [comment]
Could you provide some more details, please? I'm assuming you're compiling into a PBIT? What metadata is lost and how is that evident?

**Comment by mertbakir** [comment]
Of course, I'm using the latest Aug 2023 version of powerbi desktop. Created a .pbix file that contains the model, so it's not a thin report. Then I translated the field names usign [this tool](https://github.com/microsoft/Analysis-Services/tree/master/MetadataTranslator/Metadata%20Translator), tabular editor does the same thing.

![image](https://github.com/pbi-tools/pbi-tools/assets/43188411/f755393c-37b7-4e60-9bce-7c2a760e490e)

Saved the .pbix then used extract and compiled back into .pbit. and the translations was gone.

**Comment by mthierba** [comment]
Yes, that makes sense and is expected. Translations are currently unsupported by the latest TMDL preview. That's a TMDL limitation, not one of pbi-tools. If you switch to the legacy serialisation format for the model, you'll retain all translation metadata. This is on the backlog for TMDL, and will come by GA.

**Comment by mertbakir** [comment]
> If you switch to the legacy serialisation format for the model

Can you elaborate on this please? How do I switch, what do I lose when I switched to legacy.

**Comment by mertbakir** [comment]
Hi @mthierba is this backlog publicly available, so that I can check the current status?

**Comment by mthierba** [comment]
@mertbakir Translations support was added in Preview-7. See the full history here: https://github.com/mthierba/tmdl-example
