### ISSUE TITLE
Compatibility with Power BI Desktop (January 2023)

### ISSUE THREAD

**Issue by marektogel** [pbi-tools/pbi-tools#305]
Hi, I have a question: does pbi-tools support Power BI Desktop (January 2023)? https://www.microsoft.com/en-US/download/details.aspx?id=55330
I encountered a problem launching pbi-tools. After running the command 'pbi-tools extract,' I received a message stating that Power BI Desktop is not installed. Any recommendations?

**Comment by mthierba** [comment]
Microsoft's official support policy only covers the two most recent releases of PBI Desktop - that's what `pbi-tools` aligns with. Is there a reason why you are working with an outdated version?

**Comment by marektogel** [comment]
Thanks for your response. Just to answer your question: Yes, I have to work with this version of PBI due to compatibility reasons within my employer's company environment. Anyway, I'm happy that we're going to upgrade to PBI September 2023, which allows us to export to TMDL and source control.
