### ISSUE TITLE
Can't complie models that have been saved to TMDL by Tabular Editor 3.11.0

### ISSUE THREAD

**Issue by jobosol** [pbi-tools/pbi-tools#311]
After using save to folder with Tabular Editor 3 version 3.11.0 and then trying to compile the model using pbi-tools I'm getting this error. 

TMDL Format Error: [InvalidName] Failed to parse object name from 'relationship 36d1ebd3-ef01-421f-9eb5-3b57be3fc226'.

TE3 saves the relationships like this: 

relationship 84462af6-f2aa-420f-96c5-f36dc3f9ad9c
	fromColumn: 'Item Dimension'.'Quality Key'
	toColumn: 'Quality Dimension'.'Quality Key'

pbi-tools saves it like this 

relationship '84462af6-f2aa-420f-96c5-f36dc3f9ad9c'
	fromColumn: 'Item Dimension'.'Quality Key'
	toColumn: 'Quality Dimension'.'Quality Key'

Is this a pbi-tools bug or a TE3 bug? 

 pbi-tools info
{
  "version": "1.0.0-rc.4",
  "edition": "Desktop",
  "build": "1.0.23129.1016",
  "pbixProjVersion": "0.13",
  "pbiBuildVersion": "2.116.966.0",
  "longPathsEnabled": false,
  "amoVersion": "19.64.0.0",
  "toolPath": "C:\\Tools\\pbi-tools\\pbi-tools.exe",
  "locale": {
    "system": "nb-NO (1044)",
    "ui": "nb-NO (1044)"
  },
  "settings": {
    "PBITOOLS_LogLevel": null,
    "PBITOOLS_PbiInstallDir": null,
    "PBITOOLS_AppDataDir": null,
    "PBITOOLS_Debug": null,
    "PBITOOLS_UICulture": null,
    "PBITOOLS_EffectiveDate": null,
    "PBITOOLS_DefaultModelSerialization": null,
    "PBITOOLS_ExternalAmoPath": null
  },
  "runtime": {
    "platform": "Microsoft Windows 10.0.19045 ",
    "architecture": "X64",
    "framework": ".NET Framework 4.8.9195.0"
  }

**Comment by mthierba** [comment]
That's a known issue. The TMDL format has had a few breaking changing across different preview releases recently. For tooling interoperability it is crucial that each tool uses the exact same preview release of TMDL. There's currently a difference between TE and pbi-tool. I am about to publish a new release of pbi-tools that's using the latest TMDL version.
