### ISSUE TITLE
Issue with deploying through azure DevOps getting error

### ISSUE THREAD

**Issue by adsouza75** [pbi-tools/pbi-tools#328]
An unhandled exception occurred during deserialization.
System.NullReferenceException: Object reference not set to an instance of an object.
   at PbiTools.Serialization.TabularModelSerializer.TryDeserialize(JObject& database) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Serialization\TabularModelSerializer.cs:line 444
   at PbiTools.Serialization.PowerBIPartSerializerExtensions.DeserializeSafe[T](IPowerBIPartSerializer`1 serializer, Boolean isOptional) in X:\pbi-tools\BRANCHES\1.0.0-rc.2\src\PBI-Tools\Serialization\IPowerBIPartSerializer.cs:line 41
Generating PBIX file at '%TEMP%/0eb68da0-8210-44f3-9d29-1f0a4819cbe8/Card Management Insights 8.pbix'...

**Comment by mthierba** [comment]
Your stack trace suggests your running an outdated version of `pbi-tools`. Could you provide the output of `pbi-tools info` first?

**Comment by adsouza75** [comment]
{
  "version": "1.0.0-rc.2+20220525",
  "edition": "Core",
  "build": "1.0.22145.2342",
  "pbixProjVersion": "0.12",
  "amoVersion": "19.39.2.2",
  "toolPath": "/app/pbi-tools/pbi-tools.core",
  "locale": {
    "system": " (127)",
    "ui": " (127)"
  },
  "settings": {
    "PBITOOLS_LogLevel": null,
    "PBITOOLS_PbiInstallDir": null,
    "PBITOOLS_AppDataDir": null,
    "PBITOOLS_Debug": null,
    "PBITOOLS_UICulture": null
  },
  "runtime": {
    "platform": "Linux 6.5.0-1018-azure #19~22.04.2-Ubuntu SMP Thu Mar 21 16:45:46 UTC 2024",
    "architecture": "X64",
    "framework": ".NET 6.0.5"
  }
}

**Comment by adsouza75** [comment]
also I trying to connect to group workspace  and it say workspace ID not found , if I use api directly to deploy to that work space it works and here is manifest file that I created 

{
  "version": "0.14",
  "created": "2024-04-18T08:02:22.1654487-04:00",
  "deployments": {
      "Card Management Insights 8": {
      "mode": "dataset",
      "source": {
        "type": "Folder",
        "path": "./Card Management Insights 8"
      },
      "authentication": {
        "type": "ServicePrincipal",
        "tenantId": "",
        "clientId": "",
        "clientSecret": "%PBI_CLIENT_SECRET%"
      },
      "dataset": {
        "replaceParameters": true,
        "deployEmbeddedReport": true
      },
      "parameters": {
        "DW_Connection": "%DW_Connection%"
      },
      "options": {
        "pbiBaseUri": "https://api.powerbi.com",
        "import": {
          "nameConflict": "CreateOrOverwrite",
          "skipReport": false,
          "overrideReportLabel": true,
          "overrideModelLabel": true
        }
      },
      "logging": {},
      "environments": {
        "Development": {
            "workspace": ""
        }

      }
    }
  }
}

**Comment by adsouza75** [comment]
and  also tried with latest tag in container I see same issue 


  "version": "1.0.0-rc.8",
  "edition": "Core",
  "build": "1.0.24009.1928",
  "pbixProjVersion": "0.14",
  "amoVersion": "19.74.2.0",
  "toolPath": "/app/pbi-tools/pbi-tools.core",
  "locale": {
    "system": " (127)",
    "ui": " (127)"
  },
  "settings": {
    "PBITOOLS_LogLevel": null,
    "PBITOOLS_PbiInstallDir": null,
    "PBITOOLS_AppDataDir": null,
    "PBITOOLS_Debug": null,
    "PBITOOLS_UICulture": null,
    "PBITOOLS_EffectiveDate": null,
    "PBITOOLS_DefaultModelSerialization": null
  },
  "runtime": {
    "platform": "Linux 6.5.0-1018-azure #19~22.04.2-Ubuntu SMP Thu Mar 21 16:45:46 UTC 2024",
    "architecture": "X64",
    "framework": ".NET 6.0.26"
  }
}

**Comment by adsouza75** [comment]
able to fix it parameter needed inside option block and had to enable xmla for read/write

**Comment by NPissarra** [comment]
Hi

I'm having the same issue but my xmla is already read/write. I wounder if you can share witch parameters in options block are you refering.

My options are like this at the moment:

"options": {
        "pbiBaseUri": "https://api.powerbi.com",
        "import": {
          "nameConflict": "CreateOrOverwrite"
        },
        "refresh": {
          "enabled": true,
          "skipNewDataset": false,
          "type": "Automatic",
          "objects": {
            "Info": "Full",
            "HistoricTransactions": "None"
          },
          "tracing": {
            "enabled": true,
            "logEvents": {
              "filter": [
                "*|ReadData|*"
              ]
            },
            "summary": {
              "events": [
                "TabularRefresh"
              ],
              "objectTypes": [
                "Partition"
              ],
              "outPath": "./artifacts/refresh-summary.csv",
              "console": true
            }
          }
        },
        "dataset": {
          "replaceParameters": true,
          "deployEmbeddedReport": true
        },
        "report": {},
        "sqlScripts": {},
        "console": {}
      },

Thanks!

**Comment by adsouza75** [comment]
Here is the working 


{
  "version": "0.14",

  "created": "2024-04-18T08:02:22.1654487-04:00",
  "deployments": {
      "Reimbursement Account Insights": {
      "mode": "dataset",    
      "source": {
        "type": "Folder",
        "path": "./Reimbursement Account Insights"
      },
      "authentication": {
        "type": "ServicePrincipal",
        "tenantId": "",
        "clientId": "",
        "clientSecret": "%PBI_CLIENT_SECRET%"
      },
      "options": {
        "pbiBaseUri": "https://api.powerbi.com",
        "import": {
          "nameConflict": "CreateOrOverwrite",
          "skipReport": false,
          "overrideReportLabel": true,
          "overrideModelLabel": true
        },
        "dataset": {
          "deployEmbeddedReport": true
        }
      },
      "logging": {},
      "environments": {
        "Development": {
            "workspace": ""
        },
        "QA": {
           "workspace": ""
        },
         "Beta": {
           "workspace": ""
        },
         "Production": {
           "workspace": ""
        }

      }
    }
  }

}

**Comment by mthierba** [comment]
@NPissarra Do you still require further guidance here?

**Comment by NPissarra** [comment]
Hi, 

I still didn't find the solution. I will try again this weekend. It must be something about my configuration. I might do some question. If don't find it, I will se othe options outside of this tool. Thanks for your consern @mthierba.

**Comment by mthierba** [comment]
@NPissarra The issue is an exception that's thrown as you try to run a deployment? Could you post the error/stack trace, please?

**Comment by NPissarra** [comment]
Hei, this the error that I get:
...
Server Properties:
* CompatibilityMode           : PowerBI
* ConnectionString            : Data Source='powerbi://api.powerbi.com/v1.0/myorg/Stats test'
* DefaultCompatibilityLevel   : 1600
* Edition                     : Enterprise64
* ID                          : autopremiumhostnorwayeast000-334
* Name                        : Stats test
* SupportedCompatibilityLevels: 1200,1400,1450,1455,1460,1465,1470,1475,1480,1500,1510,1520,1530,1535,1540,1545,1550,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1600,1601,1602,1603,1604,1605,1606,1607,1608,1000000
* Version                     : 16.0.155.26
Deserializing tabular model from sources...
An unhandled exception occurred.
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at PbiTools.Deployments.DeploymentManager.<DeployDatasetAsync>d__32.MoveNext() in X:\pbi-tools\BRANCHES\1.1\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\pbi-tools\BRANCHES\1.1\src\PBI-Tools\Deployments\DeploymentManager.cs:line 112
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at PbiTools.Cli.CmdLineActions.Deploy(String folder, String label, String environment, String basePath, Boolean whatIf) in X:\pbi-tools\BRANCHES\1.1\src\PBI-Tools\Cli\Deploy.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at PowerArgs.ArgAction.Invoke()
   at PbiTools.Program.Main(String[] args) in X:\pbi-tools\BRANCHES\1.1\src\PBI-Tools\Program.cs:line 139
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at PbiTools.Deployments.DeploymentManager.<DeployDatasetAsync>d__32.MoveNext() in X:\pbi-tools\BRANCHES\1.1\src\PBI-Tools\Deployments\DeploymentManager.Dataset.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PbiTools.Deployments.DeploymentManager.<DeployAsync>d__30.MoveNext() in X:\pbi-tools\BRANCHES\1.1\src\PBI-Tools\Deployments\DeploymentManager.cs:line 112<---

**Comment by NPissarra** [comment]
The files with the datasets are in .pbix format, as I understod it should be. This files are in compatibility level 1550, should this matter?

**Comment by NPissarra** [comment]
I finally go it... the manifest file .pbixproj.json should be put in the folder of the working project. Since my original project was a .pbix file that I extracted, the folder ./Dataset got another name ./Model. So I had to correct the .pbixproj.json to the new folder name. My template manifest .pbixproj.json was created from the 'init' command.

`    "Dataset from Folder": {
      "description": "",
      "mode": "Dataset",
      "source": {
        "type": "Folder",
        "path": "./Model"`

**Comment by mthierba** [comment]
Thanks for confirming! The `.pbixproj.json` file can be placed into any folder, however, by default all relative folder and file paths inside the manifest are resolved relative to the location of the manifest file. This can be overwritten via the `-basePath` argument on the `pbi-tools deploy` command.
