### ISSUE TITLE
use_storage_api boolean not properly converted on deployment parameter

### ISSUE THREAD

**Issue by CyrilJacobPart** [pbi-tools/pbi-tools#329]
Hello,

**Context**
Trying to set [Use Storage API flag](https://learn.microsoft.com/en-us/power-query/connectors/google-bigquery
) on deployment as a parameter.

Use Storage Api	A flag that enables using the [Storage API of Google BigQuery](https://cloud.google.com/bigquery/docs/reference/storage). This option is true by default. This option can be set to false to not use the Storage API and use REST APIs instead.

**Configuration**
`"use_storage_api": true` in pbi/.pbixproj.json
use_storage_api flag boolean true is converted to `True` but is expected to be `true` in order to avoid this issue:

**Issue**
Expression.Error: The import True matches no exports. Did you miss a module reference?. . The exception was raised by the IDbCommand interface. 

**Potential Fix**
shouldn't we add  [String.ToLowerInvariant](https://learn.microsoft.com/en-us/dotnet/api/system.string.tolowerinvariant?view=net-8.0) since XML is case sensitive ? 

https://github.com/pbi-tools/pbi-tools/blob/1454b5eebf905780c35ed3ca0e9f85bb3cefb21f/src/PBI-Tools/Deployments/DeploymentParameters.cs#L180

**Comment by mthierba** [comment]
There appears to be a logic error in your M code. "The import True matches no exports." suggests that. Could you share the relevant Power query code, so I can help further?
