### ISSUE TITLE
Pbi-tool for CI & CD with single dataset and multiple reports

### ISSUE THREAD

**Issue by tapassingh** [pbi-tools/pbi-tools#332]
We use single dataset with multiple reports bind to it. I have a hard time managing it through the current git integration provided by Microsoft( they create dataset per report).

I am able to manage deployment part using pbi-tool for my requirements, however I am looking for some validation before PR gets merged and deploy.

Also instead of deploying everything, can we deploy the changed file only?

**Comment by tapassingh** [comment]
One more observation, pbi-tool deploy does not overwrite report which have same name but different dataset. Any idea, how to achieve that?

**Comment by mthierba** [comment]
Could you clarify the motivation between your two questions (selective deploy and overwrite by name)? I'd need some more details to understand your scenario better.

**Comment by tapassingh** [comment]
We have arround 9+ reports in the workplace bind to a single dataset.

When I use pbi-tool to deploy, it picks all those reports for deployment, instead of the report that gets changed.

Also when the deployment happens, it creates its own dataset. Although there is an existing report in workspace, it creates another copy. 

I am assuming, it's because, the report(s) which exists in workspace are bind to a single Symantec dataset.
