### ISSUE TITLE
Compiling PBIX after extracting and modifying role

### ISSUE THREAD

**Issue by justmike1** [pbi-tools/pbi-tools#347]
Hey guys, great project!

I would like to know if my problem is solvable via this tool, it seems very promising to be.

1. I want to extract a pbix report with a view of all the metadata inside with roles, it worked with:
```powershell
.\pbi-tools.exe extract -pbixPath .\PBI_Report_Snowflake_Live_Conn_AIG_Sample_Data.pbix
```
2. I want to edit the role expression, it worked with editing the `database` file inside `Model/`
**3. Compile back to PBIX file overwriting the old one**
**4. Push / Upload to PowerBI**

I am currently stuck on 3 & 4 as the `compile` action gives me an unsupported error. is there a workaround for it?

**Comment by mthierba** [comment]
Compiling a PBIX file from sources is an "experimental" feature, and not Microsoft supported. Moreover, compiling a valid PBIX file from sources that include a model is technically impossible (within the realms of pbi-tools).
The solution is to abandon PBIX files altogether when it comes to deployment. [`pbi-tools deploy`](https://cli.pbi.tools/deploy) works directly off extracted sources - for PBI models, it requires that the XMLA endpoint is enabled in the tenant.
Microsoft has also released pbi.onl/pbip in public preview for a similar workflow.

**Comment by justmike1** [comment]
But if I abandon PBIX files altogether then my role edit wont take into effect?

How does PowerBI expect enterprise organizations to manage role/permissions programmatically? no one is going to use the desktop to manage thousands of users?

do you know if you can you add role using DAX?

**Comment by justmike1** [comment]
I found this tool by trying to solve the problem in my most creative method I can find without failing the task.

**Comment by mthierba** [comment]
So your concern is mainly about editing RLS DAX expressions whilst continuing with Power BI Desktop? Have you considered using Tabular Editor 2? That would be the right tool for that scenario.

**Comment by justmike1** [comment]
I need to create RLS in powerbi programmatically pretty much, checking all possibilities... TabularEditor is a GUI which I can't use programmatically

**Comment by mthierba** [comment]
For programmatic manipulation of model definition you have the free [TOM library](https://learn.microsoft.com/analysis-services/tom/introduction-to-the-tabular-object-model-tom-in-analysis-services-amo). That one will work directly against the sources inside the `/SemanticModel` [PBIP](https://pbi.onl/pbip) sub-folder.
