### ISSUE TITLE
Find SSRS Installers

### ISSUE THREAD

**Issue by pfeigl** [pbi-tools/pbi-tools#50]
Hi, we are using the Power BI Report Server (on-premise). This brings it's own flavour of the PowerBI Desktop Tools with it. Most of it is seemlingly just the same, there is just a few options to deploy from the desktop tools to the report server.

However: The installation is a little different in terms of folder names and thus the installation cannot be found currently by the pbi-tools.

This is the registry path
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft Power BI Desktop SSRS\Installer`

This is the settings path:
`C:\Users\{UserName}\AppData\Local\Microsoft\Power BI Desktop SSRS`

The actual installation path seems to be this `C:\Program Files\Microsoft Power BI Desktop RS\`, however this value can be identified via the regvalue anyways.

Is there any chance you would add this lookup to the tool?

**Comment by LSTANCZYK** [comment]
I set my environment variable and tried to run extract, but it still does not work for me:
```powershell
[Environment]::SetEnvironmentVariable("PBITOOLS_PbiInstallDir", "C:\Program Files\Microsoft Power BI Desktop RS\bin", "User")
```

**Comment by mthierba** [comment]
A solution was discussed and documented in #363
