### ISSUE TITLE
Error occurs when grouped items have the same name as another group on that page

### ISSUE THREAD

**Issue by joeg76** [pbi-tools/pbi-tools#85]
Hi,

I've just downloaded and set up pbi-tools, its amazing!  Thank you for developing this.

I have found a bug in cases where a group of visuals is called X and then there is another group on that same page also called X - or an item within the X group is also called X.    It would be great if the tool could be modified to handle these situations. 

In this case, there were two items called 'Ready' which resulted in one of the items (the label 'Ready 911') missing from the compiled report.

From original source file:
![image](https://user-images.githubusercontent.com/93887373/153813829-944da9da-242d-49c2-8547-ed4f70408f71.png)
![image](https://user-images.githubusercontent.com/93887373/153813561-f9919ba3-6e96-41cd-886e-52ea947103ca.png)

In Compiled Version:
![image](https://user-images.githubusercontent.com/93887373/153813782-5e845a68-6da8-480a-ae2f-68299b0d28e2.png)
![image](https://user-images.githubusercontent.com/93887373/153813637-be5452ae-4676-44f3-a695-ebc31e15089c.png)

And then in another case (I can't past the visual because if IP but I can paste the Selections view).  In this situation there was a group called 'Shared Servers' which also had an item within that same group called 'Shared Servers'.  In the compiled version, the parent 'Shared Servers' group was missing and all the items within it collapsed up a level. ie:

Original file:
![image](https://user-images.githubusercontent.com/93887373/153814447-589f5689-7f6d-44d5-b898-42438f205263.png)

Compiled version:
![image](https://user-images.githubusercontent.com/93887373/153814550-43440d31-a74d-4349-ae54-4b9ee982f250.png)

**Comment by mthierba** [comment]
Thanks for the very detailed report. It's a particular niche case that slipped through the tests. That'll be easy to fix, though, thanks to your great example. Will most likely have an interim release with a fix mid-week.

**Comment by joeg76** [comment]
After all the work you put in to develop this the least I can do is explain clearly the issue I encountered.  Thanks for logging it as a bug, I look forward to having the fix released.

**Comment by mthierba** [comment]
@joeg76 Please grab this bugfix release: https://github.com/pbi-tools/pbi-tools/releases/tag/1.0.0-beta.9%2B220216 and test again! Fix was a one-liner, haha!

**Comment by joeg76** [comment]
The fix works I've tested it, thank you.
