### ISSUE TITLE
After compiling tables in Power Query are not in the correct groups

### ISSUE THREAD

**Issue by joeg76** [pbi-tools/pbi-tools#90]
Hey Mathias,

I've found the tools are changing the order of tables in Power Query despite the PBI file still functioning normal otherwise.  It seems to be moving tables from the group they were in to the 'Other Queries' group.
For example in the source file we have Power Query structure as follows (note 28 tables in Other Queries):

![image](https://user-images.githubusercontent.com/93887373/154878346-15997332-108f-4610-b91d-29ad7f739530.png)

![image](https://user-images.githubusercontent.com/93887373/154878405-d2fa21c5-757f-447d-b198-85d1223e7b71.png)

And in the compiled version you can see the tables from the Measures Tables have been moved to Other Queries which is now at 105 tables, as have tables from other groups as well.

![image](https://user-images.githubusercontent.com/93887373/154878555-38d878e4-98a4-47ce-bc09-b46db19036f8.png)

![image](https://user-images.githubusercontent.com/93887373/154878848-1f034077-2a9e-4e0d-a615-b657734c6712.png)

If you could look into this that would be greatly appreciated.  We are really trying to get our PBI into source control.

**Comment by mthierba** [comment]
Issue confirmed. I can replicate this.

Whilst all the query group information is held in the TMSL json, PBI Desktop doesn't fully honour all the properties in there (another example, btw, is the `isHidden` property, which needs to be provided as a custom attribute for PBI Desktop to recognize it). This is all part of the wider "Desktop Hardening" story [some of the MS guys keep talking about](https://ssbipolar.com/2021/12/17/tabular-editor-and-desktop-hardening/).

I've done a little test to dig further: Created a PBI Desktop PBIX model with query groups, exported that as a .PBIT, and extracted the .PBIT sources. This one has the additional `Mashup` part:

<img width="117" alt="image" src="https://user-images.githubusercontent.com/3763662/155008917-cbaac3c3-f179-447b-818f-cf5084b3e3a1.png">

Which also contains query group information, specifically inside `metadata.xml`:

![image](https://user-images.githubusercontent.com/3763662/155009189-afbacc55-fcad-470d-96a9-1c510c822cd9.png)

Compiling a new .PBIT from ***those*** sources produces a file with all the query groups applied correctly.

Hence, we know where to start. I'll need to do some prototyping to figure out whether the tool could generate a minimal `Mashup` part behind the scenes and inject it into the .PBIT output when no mashup sources were provided in the original sources.

No complete solution so far, but at least I know exactly where to look.

**Comment by mthierba** [comment]
I'm happy to report some success here. Worked with the PBI Desktop generated `metadata.xml` and reduced it to contain nothing but query group information:

```
<LocalPackageMetadataFile>
  <Items>
    <Item>
      <ItemLocation>
        <ItemType>AllFormulas</ItemType>
        <ItemPath />
      </ItemLocation>
      <StableEntries>
        <Entry Type="QueryGroups" Value="sBAAAAAAAAAA6Q8IeZqHpQ62e0w918/TLClBhcmFtZXRlcnMAAAAAAAAAAAAArKV1frmT3USDDMovHmRXmAZUYWJsZXMAAAEAAAAAAAAARIwkc6pW+ka/TCI3RK6U6gZQYXJlbnQAAAIAAAAAAAAAzWBWbzA0e0aJWQeFMFQpdgZOZXN0ZWQAAUSMJHOqVvpGv0wiN0SulOoAAAAA" />
      </StableEntries>
    </Item>
    <Item>
      <ItemLocation>
        <ItemType>Formula</ItemType>
        <ItemPath>Section1/HttpSource</ItemPath>
      </ItemLocation>
      <StableEntries>
        <Entry Type="QueryGroupID" Value="s1ec2433a-a166-43e9-ad9e-d30f75f3f4cb" />
      </StableEntries>
    </Item>
    <Item>
      <ItemLocation>
        <ItemType>Formula</ItemType>
        <ItemPath>Section1/Customer</ItemPath>
      </ItemLocation>
      <StableEntries>
        <Entry Type="QueryGroupID" Value="s7e75a5ac-93b9-44dd-830c-ca2f1e645798" />
      </StableEntries>
    </Item>
    <Item>
      <ItemLocation>
        <ItemType>Formula</ItemType>
        <ItemPath>Section1/Reseller</ItemPath>
      </ItemLocation>
      <StableEntries>
        <Entry Type="QueryGroupID" Value="s6f5660cd-3430-467b-8959-078530542976" />
      </StableEntries>
    </Item>
  </Items>
</LocalPackageMetadataFile>
```

Turns out, this minimal `metadata.xml` is sufficient to compile a .PBIT containing a `Mashup` part and getting the original query groups restored in PBI Desktop! Key here is that this file ***can*** be generated automatically as part of the _compile_ operation since the required information is also contained in the database.json. The exercise would be needed only to satisfy PBI Desktop.

:grinning:

**Comment by joeg76** [comment]
You are the man!   Thanks for investigating.

**Comment by joeg76** [comment]
Hi Mathias, I was wondering if you know when a release to fix this issue may be available?  
I totally understand this is an unpaid side project for you and you are under no obligation to develop anything. If a fix is coming soon it will mean my team move forward differently than if it won't be for some time, hence I wanted to ask the question.
Massively grateful for all the work you have done on pbi-tools so far.

**Comment by mthierba** [comment]
Hi Joe, really appreciate your understanding! Given the test I ran the other day, there seems to be fairly straightforward technical fix. You're lucky in the sense that my own team is impacted by the exact same issue! Being realistic and conservative, I'd say I could get a release out the weekend before SQLBits, i.e. first weekend in March. Hope that helps?

**Comment by joeg76** [comment]
That does help, thank you, we can wait.

**Comment by mthierba** [comment]
@joeg76 This was fixed in the latest release which went public a week ago. Didn't have a chance to comment here explicitly sooner (things were super busy prior to SQLBits). Hope you've had a chance to try this out yet?

**Comment by didierterrien** [comment]
Hi Mathias,
I noticed today I had the same issue. Updating to [1.0.0-rc.1 Release](https://github.com/pbi-tools/pbi-tools/projects/2#card-78045503) solved the problem.
Thanks a lot Mathias !!!
